version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb+srv://vardhanharsh824:BtYKu6e2MVLWTyLC@cluster0.zuwq6as.mongodb.net
      - JWT_SECRET=your_jwt_secret
      - JWT_REFRESH_SECRET=your_refresh_jwt_secret
    depends_on:
      - mongo
    volumes:
      - .:/app
    restart: always

  mongo:
    image: mongo:6
    container_name: mongo-1
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data:
